In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import pandas as pd
import re
from pprint import pprint
import networkx as nx
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
Graphtype = nx.DiGraph()
filepath = '/content/drive/MyDrive/GNN_datasets/edgelist.txt'
G = nx.read_edgelist(
    filepath,
    comments='#',
    create_using=Graphtype,
    nodetype=int
)

In [8]:
df = pd.read_csv('/content/drive/MyDrive/GNN_datasets/Bajaj Mall Data - Sheet1.csv')

In [9]:
df

,ID,NAME,CATEGORY,PRICE,AVGRATING
0,0,Nilkamal Arthur Double Bed Without Storage (Wa...,Beds,13999,4.2
1,1,Apka Interior Metallic Sofa cum Bed with Cushi...,Beds,21920,3.3
2,2,Springtek Folding Sofa Cum Bed - Perfect for G...,Beds,8999,2.9
3,3,Aaram by Zebrs Wooden King Size Bed Without St...,Beds,31588,4.9
4,4,Hometown Optimas King Bed With Box Storage (Da...,Beds,20368,3.5
5,5,@home by Nilkamal Nimbo Queen Bed Without Stor...,Beds,9975,3.6
6,6,@home by Nilkamal Theia High Gloss King Bed wi...,Beds,69900,3.9
7,7,Whirlpool 265 L 2 Star Frost Free Double Door ...,Fridge,26500,4.2
8,8,Haier 195 L 3 Star Direct Cool Single Door Ref...,Fridge,13499,2.1
9,9,LG 190 L 3 Star Direct Cool Single Door Refrig...,Fridge,20699,5.0
10,10,Samsung 198 L 5 Star Direct Cool Single Door R...,Fridge,21600,3.7
11,11,Whirlpool 240 L Frost Free Triple Door Refrige...,Fridge,26690,3.9
12,12,Samsung 198 3 Star Direct Cool Single Door Ref...,Fridge,15799,2.2
13,13,Samsung 253 L 3 Star Frost Free Double Door Re...,Fridge,31400,4.1
14,14,LG 260 L 2 Star Frost Free Double Door Refrige...,Fridge,25500,2.3
15,15,OPPO F21 Pro 128 GB Storage Cosmic Black (8 GB...,Smartphone,20999,4.2
16,16,OnePlus Nord CE 2 Lite 5G 128 GB Storage Blue ...,Smartphone,17999,3.3
17,17,OnePlus 11 5G 256 GB Storage Titan Black (16 G...,Smartphone,61999,4.6
18,18,Redmi 11 Prime 64 GB Storage Peppy Purple (4 G...,Smartphone,12999,3.7
19,19,Samsung Galaxy A03 32 GB Storage Black (3 GB RAM),Smartphone,10299,2.9
20,20,vivo V27 Pro 5G 128 GB Storage Noble Black (8 ...,Smartphone,37999,4.5
21,21,Realme 10 Pro+ 5G 128 GB Storage Hyperspace (8...,Smartphone,25999,4.5
22,22,Dell Intel Core i5 8 GB RAM/ 512 GB SSD/ Windo...,Laptop,55700,3.4
23,23,Dell Inspiron 3511 Intel Core i3 11th Gen8 GB ...,Laptop,43470,5.0
24,24,Dell G3-3500 Intel Core i5 10th Gen 8 GB RAM/5...,Laptop,83302,3.0
25,25,Acer Aspire Vero Green Intel Core i5 11th Gen8...,Laptop,49999,4.5
26,26,Acer Swift 3 Intel Core i5 11th Gen 8 GB RAM/ ...,Laptop,60999,4.2
27,27,Acer AMD Ryzen 5 8 GB RAM/1 TB HDD/Windows 10 ...,Laptop,61999,3.0
28,28,Lenovo IdeaPad 3 Chromebook 11IGL05 Intel Cele...,Laptop,28999,4.1
29,29,Lenovo Intel Core i3 10th Gen 8 GB RAM/ 1 TB H...,Laptop,38990,3.2

In [10]:
df['CATEGORY'].value_counts()

Fridge        8
Laptop        8
Beds          7
Smartphone    7
Name: CATEGORY, dtype: int64

In [11]:
df = df.set_index('ID')

In [12]:
nodeattrdf = df[['NAME','CATEGORY', 'PRICE', 'AVGRATING']].copy()

In [13]:
nx.set_node_attributes(G, nodeattrdf.to_dict('index'))

In [14]:
G.nodes[8]

{'NAME': 'Haier 195 L 3 Star Direct Cool Single Door Refrigerator Black Brushline (HRD-1953CKS-E)',
 'CATEGORY': 'Fridge',
 'PRICE': 13499,
 'AVGRATING': 2.1}

In [15]:
remove = [nodes for nodes in dict(G.nodes()) if len(G.nodes[nodes]) == 0]

In [17]:
G.remove_nodes_from(remove)

In [16]:
remove

[]